[[docs]]
  name = "Chapter1"
  weight = 10
  identifier = "ch1"
  url = "/chapter1/"

[[docs]]
  name = "Help"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

# [[docs]]
#   name = "Lorem"
#   weight = 70
#   identifier = "lorem"
#   url = "/docs/lorem/"

[[guide]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/guide/lorem/"

[[tutorial]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/tutorial/lorem/"

[[main]]
  name = "หนังสือ"
  url = "/docs/introduction/"
# url = "/docs/1.0/prologue/introduction/"
  weight = 10

# [[main]]
#   name = "Tutorial"
#   url = "/tutorial/lorem/ipsum/"
#   weight = 15

[[main]]
  name = "วิดีทัศน์"
  url = "/videos/"
  weight = 19

#[[main]]
#  name = "Blog"
#  url = "/blog/"
#  weight = 20

[[main]]
  name = "เริ่มต้น"
  weight = 30
  identifier = "get-started"
  url = "/docs/introduction/"

[[main]]
  name = "แบบฝึกหัด"
  weight = 40
  identifier = "exercise"
  url = "/docs/prologue/quick-start/"
  
# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
